version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.2.1

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: make lint
      - run: make test
      - run: make build
      - deploy:
          name: Deploy to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/cala-svgthumb-api-stg.git HEAD:refs/heads/master
            elif [ "${CIRCLE_BRANCH}" == "production" ]; then
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/cala-svgthumb-api-prod.git HEAD:refs/heads/master
            fi
